---

- hosts: all
  become: true
  any_errors_fatal: true  

    #roles:
    # - docker
    # - ensure_install

  tasks:
  
  - name: config kubernetes repo
    copy:
      dest: /etc/yum.repos.d/kubernetes.repo
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://pkgs.k8s.io/core:/stable:/v1.36/rpm/
        enabled=1
        gpgcheck=1
        gpgkey=https://pkgs.k8s.io/core:/stable:/v1.36/rpm/repodata/repomd.xml.key
      owner: root
      group: root
      mode: '0644'

  - name: install kubernetes packages
    package:
      name:
        - kubelet 
        - kubeadm 
        - kubectl 
      state: present

  - name: Enable and start kubelet service
    service:
      name: kubelet
      enabled: true
      state: started

- hosts: k8s_masters
  become: true
  tasks:
  - name: Open required Kubernetes ports in firewalld
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
      zone: public
    loop:
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
  
  - name: create cidr block for networking 
    shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16

  - name: generate the token and join command
    shell: "kubeadm token create --print-join-command"
    register: join_command_output


- hosts: k8s_workers
  become: true
  tasks:
  - name: run the join command from master
    shell: "{{ hostvars[groups['k8s_masters'][0]].join_command_output.stdout }}"

- hosts: k8s_masters
  become: true
  tasks:
  - name: validate installation
    shell: kubectl get nodes


